### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by Lucero7919** [unofficial-unifi/unifi-pfsense#240]
New install of Unifi, when the service tries to start, throws an error:

WARN Unable to load properties from '/usr/local/UniFi/data/system.properties' - /usr/local/UniFi/data/system.properties (No such file or directory)

Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/OSInfo
        at com.ubnt.service.system.S.<clinit>(Unknown Source)
        at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.OSInfo
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 2 more

**Comment by tong2x** [comment]
clean install?
without previous version?

java trouble shooting

Java compatibility on FreeBSD
This script may create a conflict that breaks Java on a FreeBSD upgrade. To resolve this conflict do the following:

pkg unlock -yq javavmwrapper
pkg unlock -yq java-zoneinfo
pkg unlock -yq openjdk8
pkg unlock -yq snappyjava
pkg unlock -yq snappy
pkg unlock -yq mongodb36
pkg remove -y javavmwrapper
pkg remove -y java-zoneinfo

**Comment by tong2x** [comment]
no more updates, closing
