### ISSUE TITLE
Not installing 3 packages

### ISSUE THREAD

**Issue by Iceman248** [unofficial-unifi/unifi-pfsense#287]
Python, Snappy Java, and OpenJDK don't install, haven't been able to get it working with 2.6.0. Does this just not work anymore on this version?

**Comment by lukecyca** [comment]
Same problem here on OPNsense 21.1.8_1 

```
root@opnsense:~ # uname -a
FreeBSD opnsense.dcc 12.1-RELEASE-p19-HBSD FreeBSD 12.1-RELEASE-p19-HBSD #0  0c59842367b(stable/21.1)-dirty: Mon Jul  5 15:08:43 CEST 2021     root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP  amd64
```

```
root@opnsense:~ # ./install-unifi.sh
...
Package fontconfig-2.13.94_2,1 already installed.
Package alsa-lib-1.2.2_1 already installed.
Package mpdecimal-2.5.1 already installed.
pkg: https://pkg.freebsd.org/FreeBSD:12:amd64/latest/All/python37-3.7.13_2.txz: Not Found
Package libfontenc-1.1.4 already installed.
Package mkfontscale-1.2.1 already installed.
Package dejavu-2.37_1 already installed.
Package giflib-5.2.1 already installed.
Package xorgproto-2021.5 already installed.
Package libXdmcp-1.1.3 already installed.
Package libpthread-stubs-0.4 already installed.
Package libXau-1.0.9 already installed.
Package libxcb-1.14_1 already installed.
Package libICE-1.0.10,1 already installed.
Package libSM-1.2.3,1 already installed.
Package libX11-1.7.2,1 already installed.
Package libXfixes-6.0.0 already installed.
Package libXext-1.3.4,1 already installed.
Package libXi-1.8,1 already installed.
Package libXt-1.2.1,1 already installed.
Package libXtst-1.2.3_2 already installed.
Package libXrender-0.9.10_2 already installed.
Package libinotify-20211018 already installed.
Package javavmwrapper-2.7.9 already installed.
Package java-zoneinfo-2021.e already installed.
pkg: https://pkg.freebsd.org/FreeBSD:12:amd64/latest/All/openjdk8-8.332.09.1.txz: Not Found
No packages matched for pattern 'snappyjava'

Checking integrity... done (0 conflicting)
1 packages requested for removal: 0 locked, 1 missing
pkg: https://pkg.freebsd.org/FreeBSD:12:amd64/latest/All/snappyjava-1.1.7.5.txz: Not Found
Package snappy-1.1.9_1 already installed.
Package cyrus-sasl-2.1.28 already installed.
Package icu-71.1,1 already installed.
Package boost-libs-1.72.0_7 already installed.
Package mongodb40-4.0.28 already installed.
Package unzip-6.0_8 already installed.
Package pcre-8.45_1 already installed.
```

**Comment by tong2x** [comment]
try a clean install if possible

**Comment by Iceman248** [comment]
> try a clean install if possible

I tried it on a clean install.

**Comment by tong2x** [comment]
is 2.6.0 PFsense?
try the code to remove Unifi and reinstall

**Comment by Iceman248** [comment]
> is 2.6.0 PFsense? try the code to remove Unifi and reinstall (trouble shooting guide in main page)

I did do the remove and reinstall, same issue.

**Comment by lukecyca** [comment]
I did a remove and reinstall and got the same issue.

Then I upgraded OPNsense 21.1.9_1-amd64 (FreeBSD 12.1-RELEASE-p19-HBSD), did a remove, and reinstall. Same issue.

**Comment by tong2x** [comment]
which script are you using?
try #280 or #278 
both of which I have tried
with most updates of OPNsense firmware since 21.x to 22.x

**Comment by Iceman248** [comment]
> which script are you using? try #280 or #278 both of which I have tried with most updates of OPNsense firmware since 21.x to 22.x Note: removed first old Unifi
> 
> ok seems your issues are java related apps, there is an instruction in the troubleshooting for removing java related apps
> 
> ```
> pkg unlock -yq javavmwrapper
> pkg unlock -yq java-zoneinfo
> pkg unlock -yq openjdk8
> pkg unlock -yq snappyjava
> pkg unlock -yq snappy
> pkg unlock -yq mongodb36
> pkg remove -y javavmwrapper
> pkg remove -y java-zoneinfo
> ```

I tried those commands to no avail.

**Comment by lukecyca** [comment]
I ran this:
```
pkg unlock -yq javavmwrapper
pkg unlock -yq java-zoneinfo
pkg unlock -yq openjdk8
pkg unlock -yq snappyjava
pkg unlock -yq snappy
pkg unlock -yq mongodb36
pkg remove -y javavmwrapper
pkg remove -y java-zoneinfo
```

And then immediately I tried 7.1.65 (https://tinyurl.com/527tejdj) and got the same problem:

```
...
Package fontconfig-2.13.94_2,1 already installed.
Package alsa-lib-1.2.2_1 already installed.
Package mpdecimal-2.5.1 already installed.
pkg: https://pkg.freebsd.org/FreeBSD:12:amd64/latest/All/python37-3.7.13_2.txz: Not Found
Package libfontenc-1.1.4 already installed.
Package mkfontscale-1.2.1 already installed.
Package dejavu-2.37_1 already installed.
Package giflib-5.2.1 already installed.
Package xorgproto-2021.5 already installed.
Package libXdmcp-1.1.3 already installed.
Package libpthread-stubs-0.4 already installed.
Package libXau-1.0.9 already installed.
Package libxcb-1.14_1 already installed.
Package libICE-1.0.10,1 already installed.
Package libSM-1.2.3,1 already installed.
Package libX11-1.7.2,1 already installed.
Package libXfixes-6.0.0 already installed.
Package libXext-1.3.4,1 already installed.
Package libXi-1.8,1 already installed.
Package libXt-1.2.1,1 already installed.
Package libXtst-1.2.3_2 already installed.
Package libXrender-0.9.10_2 already installed.
Package libinotify-20211018 already installed.
Package javavmwrapper-2.7.9 already installed.
Package java-zoneinfo-2021.e already installed.
pkg: https://pkg.freebsd.org/FreeBSD:12:amd64/latest/All/openjdk8-8.332.09.1.txz: Not Found
No packages matched for pattern 'snappyjava'

Checking integrity... done (0 conflicting)
1 packages requested for removal: 0 locked, 1 missing
pkg: https://pkg.freebsd.org/FreeBSD:12:amd64/latest/All/snappyjava-1.1.7.5.txz: Not Found
Package snappy-1.1.9_1 already installed.
Package cyrus-sasl-2.1.28 already installed.
Package icu-71.1,1 already installed.
Package boost-libs-1.72.0_7 already installed.
pkg: https://pkg.freebsd.org/FreeBSD:12:amd64/latest/All/mongodb42-4.2.19.txz: Not Found
Package unzip-6.0_8 already installed.
...
```

Maybe we have a problem with our FreeBSD pkg repositories or something?

**Comment by tong2x** [comment]
I have reinstalled mine, and it is having the same issue...
it is not the Unifi script, I am on Freebsd13 also... 
could the 3 apps been removed?

**Comment by microsun3000** [comment]
Can repositories https://pkg.freebsd.org/FreeBSD:12:amd64/latest/All/ be replaced with https://mirrors.xtom.nl/freebsd-pkg/FreeBSD%3A12%3Aamd64/quarterly/All/  ?

**Comment by tong2x** [comment]
yes it can in the script
it is missing some other apps
try #288 if it works for you on freebsd 12

**Comment by lukecyca** [comment]
I worked around this by manually installing each missing package:
1. Find it at https://pkg.freebsd.org/FreeBSD:12:amd64/latest/All/ and copy the URL
2. `pkg add -f <url>`
3. `pkg lock -yq <name>`
4. Then I commented out those packages in my `install-unifi.sh` script before running it so it just ignores them

Kinda hacky and brittle, but it's installed now!

My naive conclusion is that the `packagesite.txz` is referencing package files that don't exist, which indicates that the package repo is in an inconsistent state.

**Comment by microsun3000** [comment]
in pfsense 2.6 run
env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg add https://mirrors.xtom.nl/freebsd-pkg/FreeBSD%3A12%3Aamd64/quarterly/All/python37-3.7.13.pkg
env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg add https://mirrors.xtom.nl/freebsd-pkg/FreeBSD%3A12%3Aamd64/quarterly/All/snappyjava-1.1.7.5.pkg
env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg add https://mirrors.xtom.nl/freebsd-pkg/FreeBSD%3A12%3Aamd64/quarterly/All/openjdk8-8.322.06.1.pkg
env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg add https://mirrors.xtom.nl/freebsd-pkg/FreeBSD%3A12%3Aamd64/quarterly/All/mongodb36-3.6.23.pkg  
after install unifi controll 6.5.55 manually
I have successful

**Comment by tong2x** [comment]
> 3\. pkg lock -yq <name>
could you post your package install codes?
and maybe check and modify #288 last install script?

I am still having problems with Java, not installing properly
you are on opnsense?

**Comment by tong2x** [comment]
was able to install now with the following
step1
```
pkg unlock -yq python37
pkg add -f https://mirrors.xtom.nl/freebsd-pkg/FreeBSD%3A13%3Aamd64/latest/All/python37-3.7.13_2.pkg
pkg lock -yq python37

```
step2
```
pkg add -f https://mirrors.xtom.nl/freebsd-pkg/FreeBSD%3A13%3Aamd64/latest/All/openjdk8-8.332.09.1.pkg
pkg lock -yq openjdk8
```

step3
```
pkg unlock -yq snappyjava
pkg add -f https://mirrors.xtom.nl/freebsd-pkg/FreeBSD%3A13%3Aamd64/latest/All/snappyjava-1.1.7.5.pkg
pkg lock -yq snappyjava
```
step4
Install command: 
`fetch -o - https://tinyurl.com/32adap2h | sh -s`

NOTE: script is based on Unifi Network Controller 7.1.66 using the original repository with 3 app commented as suggested by @lukecyca

**Comment by tong2x** [comment]
fix for this issue, need testers to verify, please use #280, choose among the available firmwares

original code
`env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg add -f ${FREEBSD_PACKAGE_URL}${pkgname}-${pkgvers}.txz`

replaced to
`env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg add -f ${FREEBSD_PACKAGE_URL}${pkgname}-${pkgvers}.pkg`

I have notice that the issue is not really the 3 package we first thought, it is actually, "new" or updated packages that are being considered "not found" looking the code, it references to txz files, so i would assume the installation code changes in some way. to test I used #286, it successfully installed the missing packages.

we now just need to retest on other systems and other configuration.

**Comment by tong2x** [comment]
Opnsense would require another if? 
anyway we could just for now see if more systems are tested and what those system version and base is
mine is...
OPNsense 22.1.8_1-amd64
FreeBSD 13.0-STABLE

**Comment by YayPeace** [comment]
> Opnsense would require another if? anyway we could just for now see if more systems are tested and what those system version and base is mine is... OPNsense 22.1.8_1-amd64 FreeBSD 13.0-STABLE

OPNsense would need another if.
The if below should use the .pkg version when it sees "OPNsense 22" on the file "/etc/version".
```
if [ "$(cat /etc/version)" = "2.6.0-RELEASE" ]; then
    env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg add -f ${FREEBSD_PACKAGE_URL}${pkgname}-${pkgvers}.pkg
elif [grep -q "OPNsense 22" "/etc/version"]; then
    env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg add -f ${FREEBSD_PACKAGE_URL}${pkgname}-${pkgvers}.pkg
else
    env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg add -f ${FREEBSD_PACKAGE_URL}${pkgname}-${pkgvers}.txz
fi
```
Yeah, lets wait for more system versions.

**Comment by the2Faces** [comment]
Question,

does it not suffice, just to replace the *.txz extention with pkg?
For what the *.txz extention is needed in particular?

P.S. I'm not a pro within scripting and programming, only messing around with OPNSense and Unifi controllers.

**Comment by tong2x** [comment]
*.txz i think is an archive format of the package, I guess its purpose is for "faster" download. for now the script is just changed via the replacement of txz to pkg. pending more test devices and platforms

**Comment by TheDave94** [comment]
When I try to update to 7.2.85 on OPNsense 22.1.8_1 I get this error:

root@OPNsense:~ # WARN Unable to load properties from '/usr/local/UniFi/data/system.properties' - /usr/local/UniFi/data/system.properties (No such file or directory)
Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/OSInfo
	at com.ubnt.service.system.IA.<clinit>(Unknown Source)
	at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.OSInfo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more

Any idea how to fix this?

**Comment by TheDave94** [comment]
Thanks I got it working by manually installing snappyjava, no idea what went wrong in the first place

**Comment by ilium007** [comment]
Same issue on fresh OPNsense install and updated. Errors below are what I have found in the stdout

```
pkg: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/python37-3.7.13_2.txz: Not Found
pkg: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mkfontscale-1.2.1.txz: Not Found
pkg: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/dejavu-2.37_1.txz: Not Found

pkg: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/openjdk8-8.332.09.1.txz: Not Found
Updating database digests format: 100%
No packages matched for pattern 'snappyjava'

1 packages requested for removal: 0 locked, 1 missing
pkg: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/snappyjava-1.1.7.5.txz: Not Found
Fetching snappy-1.1.9_1.txz: 100%   30 KiB  30.6kB/s    00:01
Installing snappy-1.1.9_1...
Extracting snappy-1.1.9_1: 100%

pkg: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/boost-libs-1.79.0_1.txz: Not Found
pkg: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mongodb40-4.0.28_1.txz: Not Found
```

**Comment by trucktire** [comment]
Hi. I was hoping someone could help a noob out. I wanted to get this to work but had the install problem as well. So I followed 

> was able to install now with the following step1
> 
> ```
> pkg unlock -yq python37
> pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/python37-3.7.13_2.pkg
> pkg lock -yq python37
> ```
> 
> step2
> 
> ```
> pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/openjdk8-8.332.09.1.pkg
> pkg lock -yq openjdk8
> ```
> 
> step3
> 
> ```
> pkg unlock -yq snappyjava
> pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/snappyjava-1.1.7.5.pkg
> pkg lock -yq snappyjava
> ```
> 
> step4 Install command: `fetch -o - https://tinyurl.com/32adap2h | sh -s` from #288
> 
> NOTE: script is based on Unifi Network Controller 7.1.66 using the original repository with 3 app commented as suggested by @lukecyca hope the inconsistency or issue with the repository be resolved

and then 


> So my workaround was installing all the not found packages manually:
> 
> ```
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/snappyjava-1.1.7.5.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/dejavu-2.37_1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mkfontscale-1.2.1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/freetype2-2.12.1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/fontconfig-2.13.94_2,1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/python37-3.7.13_2.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mkfontscale-1.2.1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/dejavu-2.37_1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/openjdk8-8.332.09.1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/snappyjava-1.1.7.5.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/boost-libs-1.79.0_1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mongodb40-4.0.28_1.pkg
> ```
> 
> and then re-run the install-script.
> 
> Afterwards I got this message `WARN Unable to load properties from '/usr/local/UniFi/data/system.properties' - /usr/local/UniFi/data/system.properties (No such file or directory)`. The webserver is now answering but showing `HTTP Status 404 – Not Found`
> 
> THEN restart OS and its working

and I "kinda" got it to work. When I go to "pfsense-ipadress:8443" I get a message that says "data migration in progress" and that message has been there for a couple hours now? I don't know how to progress? Is there anyone here who could help me out please?
Thanks

**Comment by tong2x** [comment]
> Hi. I was hoping someone could help a noob out. I wanted to get this to work but had the install problem as well. So I followed
> 
> > was able to install now with the following step1
> > ```
> > pkg unlock -yq python37
> > pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/python37-3.7.13_2.pkg
> > pkg lock -yq python37
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > step2
> > ```
> > pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/openjdk8-8.332.09.1.pkg
> > pkg lock -yq openjdk8
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > step3
> > ```
> > pkg unlock -yq snappyjava
> > pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/snappyjava-1.1.7.5.pkg
> > pkg lock -yq snappyjava
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > step4 Install command: `fetch -o - https://tinyurl.com/32adap2h | sh -s` from #288
> > NOTE: script is based on Unifi Network Controller 7.1.66 using the original repository with 3 app commented as suggested by @lukecyca hope the inconsistency or issue with the repository be resolved
> 
> and then
> 
> > So my workaround was installing all the not found packages manually:
> > ```
> >  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/snappyjava-1.1.7.5.pkg
> >  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/dejavu-2.37_1.pkg
> >  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mkfontscale-1.2.1.pkg
> >  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/freetype2-2.12.1.pkg
> >  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/fontconfig-2.13.94_2,1.pkg
> >  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/python37-3.7.13_2.pkg
> >  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mkfontscale-1.2.1.pkg
> >  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/dejavu-2.37_1.pkg
> >  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/openjdk8-8.332.09.1.pkg
> >  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/snappyjava-1.1.7.5.pkg
> >  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/boost-libs-1.79.0_1.pkg
> >  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mongodb40-4.0.28_1.pkg
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then re-run the install-script.
> > Afterwards I got this message `WARN Unable to load properties from '/usr/local/UniFi/data/system.properties' - /usr/local/UniFi/data/system.properties (No such file or directory)`. The webserver is now answering but showing `HTTP Status 404 – Not Found`
> > THEN restart OS and its working
> 
> and I "kinda" got it to work. When I go to "pfsense-ipadress:8443" I get a message that says "data migration in progress" and that message has been there for a couple hours now? I don't know how to progress? Is there anyone here who could help me out please? Thanks

could you detail the system os you are using or firmware version¿ (opnsense pfsense or others?)
and if you saw the exact error what was it?
which version of unifi script you used?

as for db migration, usually after waiting a couple of hours, just revisit the site.
if it persits, run code to stop unifi then start it again (or reboot)
thst is what i do usually

**Comment by trucktire** [comment]
> could you detail the system os you are using or firmware version¿ (opnsense pfsense or others?) and if you saw the exact error what was it? which version of unifi script you used?
> 
> as for db migration, usually after waiting a couple of hours, just revisit the site. if it persits, run code to stop unifi then start it again (or reboot) thst is what i do usually

Sure. I run Pfsense 2.6.0 on home built hardware with an intel I3 and 8 gigs of ram.
I don't know if it counts as an error but when I went to "pfsense-ipadress:8443" I got a message that says "data migration in progress" in clean text and it wouldn't go away and give me the network application.

however, I finally gave up and did a full reinstall of pfsense to try iagain. Something might have gone wrong when I installed all the packages so I figured it was easiest to make a new install.

So, could you maybe tell me if there is a trick to get it to work?
I followed the instructions on the "code" page but it didn't work. I then tried some of the stuff on this page but it didn't help?

**Comment by tong2x** [comment]
on clean install run this is pfsense shell
`fetch -o - https://tinyurl.com/3h2czt7e | sh -s`

to clean install first, run the following... (maybe reboot to make sure)
```
rm -rf /usr/local/UniFi
rm /usr/local/etc/rc.d/unifi.sh
```

best to check/see the errors or run the script with the following code so the install could logs could be fetch
`fetch -o - https://tinyurl.com/3h2czt7e | sh -s cmd |& tee unifi7285.txt`
you will need to press ctr+x to terminate the install script

**Comment by trucktire** [comment]
> sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/snappyjava-1.1.7.5.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/dejavu-2.37_1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mkfontscale-1.2.1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/freetype2-2.12.1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/fontconfig-2.13.94_2,1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/python37-3.7.13_2.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mkfontscale-1.2.1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/dejavu-2.37_1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/openjdk8-8.332.09.1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/snappyjava-1.1.7.5.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/boost-libs-1.79.0_1.pkg
>  sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mongodb40-4.0.28_1.pkg

Hi. I tried your install line. these are missing.

sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/snappyjava-1.1.7.5.pkg
 sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/dejavu-2.37_1.pkg
 sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mkfontscale-1.2.1.pkg
 sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/freetype2-2.12.1.pkg
 sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/fontconfig-2.13.94_2,1.pkg
 sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/python37-3.7.13_2.pkg
 sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mkfontscale-1.2.1.pkg
 sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/dejavu-2.37_1.pkg
 sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/openjdk8-8.332.09.1.pkg
 sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/snappyjava-1.1.7.5.pkg
 sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/boost-libs-1.79.0_1.pkg
 sudo pkg add -f https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/mongodb40-4.0.28_1.pkg

I tried adding them manually. We'll see how it goes.

**Comment by trucktire** [comment]
I have been messing around, trying to get it to work. But I'm stuck now. The unifi service refuses to start. When I run "service unifi.sh start" I get "port 8080 not available". I can see with "lsof -i :8080" that java is holding up there. I have tried to use "kill" on java pid and running "service unifi.sh start"quickly, but it isn't working. I have also tried running the Java compatibility code in troubleshooting. But then I get java error when trying to run "service unifi.sh start" and need to reinstall all java related stuff to get that to disappear. I don't know what to do? Is it possible to move java to another port or something?

**Comment by tong2x** [comment]
usually the issue with port 8080 not available is resolved by
running the command
`service unifi.sh stop`
follow by the start, to restart service
`service unifi.sh start`
there are cases though that you may need to hard restart (turn off your device then back on)
and see if that changes the status of unifi

ok, it seem the install script I sent was using the old code at has the "missing" pkg, very sorry for that, 
for clean install run the following...
```
rm -rf /usr/local/UniFi
rm /usr/local/etc/rc.d/unifi.sh
fetch -o - https://tinyurl.com/4rz8ycwz | sh -s cmd |& tee unifi7285.txt
```
you may omit the RM command to just reupdate the install if you want.

**Comment by trucktire** [comment]
[Thank you very much.
It immediately worked without a hitch :)

**Comment by shaneallgeier** [comment]
FYI: I made a PR that fixes this issue (#290)
